# Localhost
###
# Get All
GET http://localhost:5959/contacts
###
# Get One
GET http://localhost:5959/contacts/66edb9f6197f79d02a63c74c
###

### Create new contact
POST http://localhost:5959/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Created",
    "lastName": "Contact",
    "email": "newcontact@testing.com",
    "birthday": "1993-02-05T00:00:00.000Z",
    "favoriteColor": "test"
}

### Update contact
PUT http://localhost:5959/contacts/66f87a45a4e308354517dc9c HTTP/1.1
Content-Type: application/json

{
    "firstName": "Updated",
    "lastName": "Contact",
    "email": "newcontact@testing.com",
    "birthday": "1993-02-05T00:00:00.000Z",
    "favoriteColor": "test"
}

### Delete contact
DELETE http://localhost:5959/contacts/66f87ad1a4e308354517dc9f HTTP/1.1

# Production
###
# Get All
GET https://cse341-0z9m.onrender.com/contacts
###
# Get One
GET https://cse341-0z9m.onrender.com/contacts/66edb9f6197f79d02a63c74c

### Post
POST https://cse341-0z9m.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Created",
    "lastName": "Contact",
    "email": "newcontact@testing.com",
    "birthday": "1993-02-05T00:00:00.000Z",
    "favoriteColor": "test"
}

### Update contact
PUT https://cse341-0z9m.onrender.com/contacts/66f87a45a4e308354517dc9c HTTP/1.1
Content-Type: application/json

{
    "firstName": "Updated",
    "lastName": "Contact",
    "email": "newcontact@testing.com",
    "birthday": "1993-02-05T00:00:00.000Z",
    "favoriteColor": "test"
}

### Delete contact
DELETE https://cse341-0z9m.onrender.com/contacts/66f87ad1a4e308354517dc9f HTTP/1.1